Active user export endpoint for SOV
ImperialCollegeLondon/imperial_coldfront_plugin pull request #57
Opened 2024-12-15 09:12 UTC by AdrianDAlessandro

# Description

Opening in draft to confirm I am on the right track.

This PR provides an endpoint to get the active user details in passwd format.

I have made this an endpoint that requires login and is a JSONResponse because that feels more correct than what is currently in SelfService (no-login required and a plain text response). I can revert that commit, if needed.

On observation is that the UnixUID is not guaranteed to exist for every user that is in a group, but it _should_.

Outstanding tasks:
- [ ] More thorough tests
- [ ] Ensure UnixUID exists

Fixes #35

## Type of change

- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass (eg. `python -m pytest`)
- [ ] The documentation builds and looks OK (eg. `python -m sphinx -b html docs docs/build`)
- [ ] Pre-commit hooks run successfully (eg. `pre-commit run --all-files`)

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

2024-12-16 11:49 UTC, cc-a requested changes
Thanks for this @AdrianDAlessandro. Unfortunately the format is the format and we have no say in it so please do role back the json changes.

The potential for missing uid's is something we need to deal with but not sure quite how yet. For the purposes of this PR the only way I'd address it is that the view should continue to function if a uid is missing for a user.

2024-12-19 16:41 UTC, jamesturner246 commented on imperial_coldfront_plugin/views.py
> +        uid = UnixUID.objects.get(user=user)
Are reverse accessors always made on models when adding any type of relation to a model on related models?

2024-12-19 16:41 UTC, jamesturner246 commented on imperial_coldfront_plugin/views.py
> +        passwd += format_str.format(user=user, uid=uid, group=group)
This is effectively generating and returning a new `passwd` file for *everyone* registered at Imperial and associated with a group, right? Besides it being converted to JSON right now.

2025-01-10 14:12 UTC, AdrianDAlessandro commented on imperial_coldfront_plugin/views.py
> +        passwd += format_str.format(user=user, uid=uid, group=group)
The entire view is doing that, yes. This particular for loop is picking out PIs that own a group but aren't also members of a group.

2025-01-10 14:30 UTC, AdrianDAlessandro commented on imperial_coldfront_plugin/views.py
> +    qs = User.objects.filter(groupmembership__member__isnull=False).distinct()
Changed to `groupmembership__isnull=False`

2025-01-10 14:30 UTC, AdrianDAlessandro commented on imperial_coldfront_plugin/views.py
> +        uid = UnixUID.objects.get(user=user)
Done, didn't realise you could also use reverse accessors like this and not just in filer queries.

2025-01-10 14:30 UTC, AdrianDAlessandro commented on imperial_coldfront_plugin/views.py
> +    )
It doesn't really makes sent to use a template for this to me. It's not a user-facing page, and should never really be viewed in html. So adding in the extra complexity to hide the output format behind a html template doesn't feel right.

I can make the change if you insist, but I think templates should only be used for webpages and components that are viewed by users of the site.

2025-01-14 17:06 UTC, cc-a commented on imperial_coldfront_plugin/views.py
> +@login_required
Actually needs to be accessible to non-authorised users

2025-01-14 17:15 UTC, cc-a requested changes
Thanks for this. A few minor nits.

2025-01-15 17:01 UTC, AdrianDAlessandro commented on imperial_coldfront_plugin/views.py
> +@login_required
This feels like a massive security hole... but ok

2025-01-15 17:01 UTC, AdrianDAlessandro commented on tests/test_views.py
> +        assert len(psswd_list) == 2
The newline character at the end results in an empty string as the final element in the list

2025-01-15 17:01 UTC, AdrianDAlessandro commented on tests/test_views.py
> +        assert psswd_list[0] == expected
I'm not sure what you mean by this

2025-01-15 17:30 UTC, cc-a approved these changes

2025-01-15 17:31 UTC, merged